language: python
python:
  - "3.3"
  - "3.4"
#  - "nightly" # currently points to 3.6-dev

  # command to install dependencies
install:  "pip install ."
# command to run tests
script:
  - nosetests --with-doctest
  - ceviz --help
  - tdviz --help
  - invtbl2smv share/invtbl.csv
